---
title: "For Bioconductor Package Maintainers"
description: >
  Learn how Bioconductor package maintainers can get involved.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{For Bioconductor Package Maintainers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Request for Your Sweave document to be Converted to Rmd

If you're a Bioconductor package maintainer and would like help converting your
package's Sweave vignettes to `.Rmd`, you're welcome to open an issue in your
GitHub repository and ask `@Bioconductor/sweave2rmd` to convert specific files.

We will put your request on our
[Sweave2rmd Project Board](https://github.com/orgs/Bioconductor/projects/2/views/1).
We will convert the files to `.Rmd`. The new vignette will be rendered in
`HTML`.  We will also review the conversion internally before sending it back
to you for your approval via a pull request.

## Convert Your Own Vignettes

If you prefer to convert your own vignettes, see our Contribute document for
helpful tips to help with your conversion.

## Before Accepting a Pull Request

Please wait for Sweave2Rmd volunteers to review the pull request internally so
that they can address any issues that are not specific to your package. When
the pull request has passed an internal review, a volunteer will request that
you as the maintainer review the pull request to request any additional
changes if necessary to accept it.

## Squash and Merge a Pull Request

After a pull request has passed your review as a maintainer, you should merge
the request on GitHub, using the `squash and merge` option to reduce the commit
history.

## After Merging

We recommend that you

* run `BiocCheck` on the package and making any changes in a separate pull request
* update the NEWS file in a separate commit
* bump the version in the `DESCRIPTION` in a separate commit so that the build
  system will recognize that a new version is available to build

You should follow the usual workflow of package development described at
[Bioconductor Packages: Development, Maintenance, and Peer Review](https://contributions.bioconductor.org/git-version-control.html)
to push to the Bioconductor repository.
